language: python
dist: trusty
python:
  - 2.7
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: "pip install gevent lmdb msgpack-python"
script: python tests.py
